/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem;

/**
 *
 * @author User
 */
public class Helicopter extends javax.swing.JFrame implements Obsever{
    
    MainController mainController;
    /**
     * Creates new form Helicopter
     */
    public Helicopter(MainController mainController) {
        initComponents();
        setLocation(770, 335);
        this.mainController=mainController;
        buttonsEnable(heliCheckBox.isSelected());
        setVisible(true);
    }
    
    @Override
    public void setAreaClear(boolean isChecked){
        if(isChecked){
            heliTextFieldClear.setText("Area is Cleared");
        }else{
            heliTextFieldClear.setText("Area is not Cleared");
        }
    }

    @Override
    public void setMessage(String message){
      heliTextArea.setText(heliTextArea.getText().isEmpty()? message:heliTextArea.getText()+"\n"+message);
    }
    
    @Override
    public String toString(){
        return "Helicopter";
    }
    
    @Override
    public void setEnableButtons(int value){
        if(value>20){
            heliBtnShoot.setEnabled(true);
        }else{
            heliBtnShoot.setEnabled(false);
        }
        
        if(value>40){
            heliBtnMissile.setEnabled(true);
        }else{
            heliBtnMissile.setEnabled(false);
        }
        
        if(value>60){
            heliBtnLaser.setEnabled(true);
        }else{
            heliBtnLaser.setEnabled(false);
        }
        
        buttonsEnable(heliCheckBox.isSelected());
       
    }
    
    public void buttonsEnable(boolean status){
        if(!status){
            heliBtnShoot.setEnabled(false);
            heliBtnMissile.setEnabled(false);
            heliBtnLaser.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heliLabel = new javax.swing.JLabel();
        heliBtnShoot = new javax.swing.JButton();
        heliBtnMissile = new javax.swing.JButton();
        heliBtnLaser = new javax.swing.JButton();
        heliCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        heliTextArea = new javax.swing.JTextArea();
        heliTextFieldMsg = new javax.swing.JTextField();
        heliBtnSend = new javax.swing.JButton();
        heliTextFieldClear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(500, 330));

        heliLabel.setBackground(new java.awt.Color(0, 153, 153));
        heliLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        heliLabel.setForeground(new java.awt.Color(255, 255, 255));
        heliLabel.setText("  Helicopter");
        heliLabel.setOpaque(true);

        heliBtnShoot.setText("Shoot");
        heliBtnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliBtnShootActionPerformed(evt);
            }
        });

        heliBtnMissile.setText("Missile Operation");
        heliBtnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliBtnMissileActionPerformed(evt);
            }
        });

        heliBtnLaser.setText("Laser Operation");
        heliBtnLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliBtnLaserActionPerformed(evt);
            }
        });

        heliCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        heliCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        heliCheckBox.setText("Position");
        heliCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliCheckBoxActionPerformed(evt);
            }
        });

        heliTextArea.setColumns(20);
        heliTextArea.setRows(5);
        jScrollPane1.setViewportView(heliTextArea);

        heliTextFieldMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliTextFieldMsgActionPerformed(evt);
            }
        });

        heliBtnSend.setText("Send");
        heliBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliBtnSendActionPerformed(evt);
            }
        });

        heliTextFieldClear.setBackground(new java.awt.Color(255, 255, 204));
        heliTextFieldClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        heliTextFieldClear.setText("Area is Not Cleared");
        heliTextFieldClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heliTextFieldClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heliLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(heliTextFieldClear, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heliBtnLaser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(heliCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(heliBtnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(heliBtnMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(heliTextFieldMsg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(heliBtnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(heliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heliTextFieldClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heliBtnMissile)
                    .addComponent(heliBtnShoot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heliBtnLaser)
                    .addComponent(heliCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heliTextFieldMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heliBtnSend, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void heliBtnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliBtnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliBtnShootActionPerformed

    private void heliBtnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliBtnMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliBtnMissileActionPerformed

    private void heliBtnLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliBtnLaserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliBtnLaserActionPerformed

    private void heliTextFieldMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliTextFieldMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliTextFieldMsgActionPerformed

    private void heliBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliBtnSendActionPerformed
        mainController.obseverMessage("Helicopter", heliTextFieldMsg.getText());
        heliTextFieldMsg.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_heliBtnSendActionPerformed

    private void heliTextFieldClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliTextFieldClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliTextFieldClearActionPerformed

    private void heliCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heliCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heliCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton heliBtnLaser;
    private javax.swing.JButton heliBtnMissile;
    private javax.swing.JButton heliBtnSend;
    private javax.swing.JButton heliBtnShoot;
    private javax.swing.JCheckBox heliCheckBox;
    private javax.swing.JLabel heliLabel;
    private javax.swing.JTextArea heliTextArea;
    private javax.swing.JTextField heliTextFieldClear;
    private javax.swing.JTextField heliTextFieldMsg;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
