/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem;

/**
 *
 * @author User
 */
public class MainController extends javax.swing.JFrame {
    Observable observable;
    /**
     * Creates new form MainController
     */
    public MainController(Observable observable) {
        initComponents();        
        setLocation(220, 10);
        this.observable=observable;
        setVisible(true);
        mainComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General","Helicopter","Submarine","Tank" }));
    }
 
    public void obseverMessage(String obsever,String message){
        mainTextArea.setText(mainTextArea.getText().isBlank() ? obsever+" : "+message: mainTextArea.getText()+"\n"+obsever+" : "+message);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSlider = new javax.swing.JSlider();
        mainTextField = new javax.swing.JTextField();
        mainCheckBox = new javax.swing.JCheckBox();
        mainLabel = new javax.swing.JLabel();
        mainBtnSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        mainPrivateCheckBox = new javax.swing.JCheckBox();
        mainComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setPreferredSize(new java.awt.Dimension(500, 330));

        mainSlider.setMajorTickSpacing(20);
        mainSlider.setPaintLabels(true);
        mainSlider.setPaintTicks(true);
        mainSlider.setValue(0);
        mainSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainSliderStateChanged(evt);
            }
        });

        mainCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        mainCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        mainCheckBox.setText("Area Clear");
        mainCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainCheckBoxActionPerformed(evt);
            }
        });

        mainLabel.setBackground(new java.awt.Color(0, 102, 51));
        mainLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        mainLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainLabel.setText(" Main Controller");
        mainLabel.setOpaque(true);

        mainBtnSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainBtnSend.setText("Send");
        mainBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnSendActionPerformed(evt);
            }
        });

        mainTextArea.setColumns(20);
        mainTextArea.setRows(5);
        jScrollPane2.setViewportView(mainTextArea);

        mainPrivateCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        mainPrivateCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        mainPrivateCheckBox.setText("Send Private");
        mainPrivateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPrivateCheckBoxActionPerformed(evt);
            }
        });

        mainComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mainComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPrivateCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainBtnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)
                        .addComponent(mainCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPrivateCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainBtnSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainCheckBoxActionPerformed
        observable.areaClear(mainCheckBox.isSelected());
        // TODO add your handling code here:
    }//GEN-LAST:event_mainCheckBoxActionPerformed

    private void mainBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnSendActionPerformed
        if(mainPrivateCheckBox.isSelected()){
            observable.sendPrivateMessage("Main Controller : "+mainTextField.getText(), (String)mainComboBox.getSelectedItem());
        }else{
            observable.sendMessage("Main Controller : "+mainTextField.getText());  
        }
        mainTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_mainBtnSendActionPerformed

    private void mainPrivateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPrivateCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPrivateCheckBoxActionPerformed

    private void mainSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainSliderStateChanged
        observable.buttonController(mainSlider.getValue());
// TODO add your handling code here:
    }//GEN-LAST:event_mainSliderStateChanged

    private void mainComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainComboBoxActionPerformed
                                           
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mainBtnSend;
    private javax.swing.JCheckBox mainCheckBox;
    private javax.swing.JComboBox<String> mainComboBox;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JCheckBox mainPrivateCheckBox;
    private javax.swing.JSlider mainSlider;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JTextField mainTextField;
    // End of variables declaration//GEN-END:variables
}
