/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem;

/**
 *
 * @author User
 */
public class Submarine extends javax.swing.JFrame implements Obsever{
   
    MainController mainController;
    
    /**
     * Creates new form Submarine
     */
    public Submarine(MainController mainController) {
        initComponents();
        setLocation(770, 10);
        this.mainController=mainController;
        buttonsEnable(subCheckBox.isSelected());
        setVisible(true);
    }
    
    @Override
    public void setAreaClear(boolean isChecked){
     if(isChecked){
            subTextFieldClear.setText("Area is Cleared");
        }else{
            subTextFieldClear.setText("Area is not Cleared");
        }   
    }
    
    @Override
    public void setMessage(String message){
        subTextArea.setText(subTextArea.getText().isEmpty()? message:subTextArea.getText()+"\n"+message);
    }
    
    @Override
    public String toString(){
        return "Submarine";
    }
    
    @Override
    public void setEnableButtons(int value){
        if(value>20){
            subBtnShoot.setEnabled(true);
        }else{
            subBtnShoot.setEnabled(false);
        }
        
        if(value>40){
            subBtnSonar.setEnabled(true);
        }else{
            subBtnSonar.setEnabled(false);
        }
        
        if(value>60){
            subBtnMissile.setEnabled(true);
        }else{
            subBtnMissile.setEnabled(false);
        }
        
        if(value>80){
            subBtnTrident.setEnabled(true);
        }else{
            subBtnTrident.setEnabled(false);
        }
        
    buttonsEnable(subCheckBox.isSelected());
    }
    
    public void buttonsEnable(boolean status){
        if(!status){
            subBtnShoot.setEnabled(false);
            subBtnSonar.setEnabled(false);
            subBtnMissile.setEnabled(false);
            subBtnTrident.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subLabel = new javax.swing.JLabel();
        subTextFieldClear = new javax.swing.JTextField();
        subBtnShoot = new javax.swing.JButton();
        subBtnSonar = new javax.swing.JButton();
        subBtnMissile = new javax.swing.JButton();
        subBtnTrident = new javax.swing.JButton();
        subCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        subTextArea = new javax.swing.JTextArea();
        subTextFieldMsg = new javax.swing.JTextField();
        subBtnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 330));

        subLabel.setBackground(new java.awt.Color(0, 153, 153));
        subLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        subLabel.setForeground(new java.awt.Color(255, 255, 255));
        subLabel.setText("  Submarine");
        subLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subLabel.setOpaque(true);

        subTextFieldClear.setBackground(new java.awt.Color(255, 255, 204));
        subTextFieldClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subTextFieldClear.setText("Area is Not Cleared");
        subTextFieldClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTextFieldClearActionPerformed(evt);
            }
        });

        subBtnShoot.setText("Shoot");
        subBtnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnShootActionPerformed(evt);
            }
        });

        subBtnSonar.setText("Sonar Operation");
        subBtnSonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnSonarActionPerformed(evt);
            }
        });

        subBtnMissile.setText("Toahawk Missile");
        subBtnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnMissileActionPerformed(evt);
            }
        });

        subBtnTrident.setText("Trident-2 Missile");
        subBtnTrident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnTridentActionPerformed(evt);
            }
        });

        subCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        subCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        subCheckBox.setText("Position");
        subCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCheckBoxActionPerformed(evt);
            }
        });

        subTextArea.setColumns(20);
        subTextArea.setRows(5);
        jScrollPane1.setViewportView(subTextArea);

        subTextFieldMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTextFieldMsgActionPerformed(evt);
            }
        });

        subBtnSend.setText("Send");
        subBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTextFieldClear, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subBtnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subBtnSonar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subTextFieldMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subBtnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(subBtnMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subBtnTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(subLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subTextFieldClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subBtnShoot)
                            .addComponent(subBtnSonar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subBtnMissile)
                            .addComponent(subBtnTrident)
                            .addComponent(subCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTextFieldMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subBtnSend))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subBtnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtnShootActionPerformed

    private void subBtnSonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnSonarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtnSonarActionPerformed

    private void subBtnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtnMissileActionPerformed

    private void subBtnTridentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnTridentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtnTridentActionPerformed

    private void subTextFieldMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTextFieldMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTextFieldMsgActionPerformed

    private void subBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnSendActionPerformed
        mainController.obseverMessage("Submarine", subTextFieldMsg.getText());
        subTextFieldMsg.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtnSendActionPerformed

    private void subCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subCheckBoxActionPerformed

    private void subTextFieldClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTextFieldClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTextFieldClearActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton subBtnMissile;
    private javax.swing.JButton subBtnSend;
    private javax.swing.JButton subBtnShoot;
    private javax.swing.JButton subBtnSonar;
    private javax.swing.JButton subBtnTrident;
    private javax.swing.JCheckBox subCheckBox;
    private javax.swing.JLabel subLabel;
    private javax.swing.JTextArea subTextArea;
    private javax.swing.JTextField subTextFieldClear;
    private javax.swing.JTextField subTextFieldMsg;
    // End of variables declaration//GEN-END:variables

}
