/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem;

/**
 *
 * @author User
 */
public class Tank extends javax.swing.JFrame implements Obsever{
 
    MainController mainController;
    /**
     * Creates new form Tank
     */
    public Tank(MainController mainController) {
        initComponents();
        setLocation(220, 335);
        this.mainController=mainController;
        buttonsEnable(tankCheckBox.isSelected());
        setVisible(true);
    }
    
    @Override
    public void setAreaClear(boolean isChecked){
        if(isChecked){
            tankTextFieldClear.setText("Area is Cleared");
        }else{
            tankTextFieldClear.setText("Area is not Cleared");
        }
    }
    
    @Override
    public void setMessage(String message){
        tankTextArea.setText(tankTextArea.getText().isEmpty()? message:tankTextArea.getText()+"\n"+message);
    }
    
    @Override
    public String toString(){
        return "Tank";
    }
    
    @Override
    public void setEnableButtons(int value){
        if(value>20){
            tankBtnShoot.setEnabled(true);
        }else{
            tankBtnShoot.setEnabled(false);
        }
        
        if(value>40){
            tankBtnMissile.setEnabled(true);
        }else{
            tankBtnMissile.setEnabled(false);
        }
        
        if(value>60){
            tankBtnRadar.setEnabled(true);
        }else{
            tankBtnRadar.setEnabled(false);
        }
        
        if(value>80){
            tankBtnRotate.setEnabled(true);
        }else{
            tankBtnRotate.setEnabled(false);
        }
        
        buttonsEnable(tankCheckBox.isSelected());
        
    }
    
    public void buttonsEnable(boolean status){
        if(!status){
            tankBtnShoot.setEnabled(false);
            tankBtnMissile.setEnabled(false);
            tankBtnRadar.setEnabled(false);
            tankBtnRotate.setEnabled(false);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tankLabel = new javax.swing.JLabel();
        tankTextFieldClear = new javax.swing.JTextField();
        tankBtnShoot = new javax.swing.JButton();
        tankBtnMissile = new javax.swing.JButton();
        tankBtnRadar = new javax.swing.JButton();
        tankBtnRotate = new javax.swing.JButton();
        tankCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tankTextArea = new javax.swing.JTextArea();
        tankTextFieldMsg = new javax.swing.JTextField();
        tankBtnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 330));

        tankLabel.setBackground(new java.awt.Color(0, 153, 153));
        tankLabel.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        tankLabel.setForeground(new java.awt.Color(255, 255, 255));
        tankLabel.setText("  Tank");
        tankLabel.setOpaque(true);

        tankTextFieldClear.setBackground(new java.awt.Color(255, 255, 204));
        tankTextFieldClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tankTextFieldClear.setText("Area is Not Cleared");
        tankTextFieldClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankTextFieldClearActionPerformed(evt);
            }
        });

        tankBtnShoot.setText("Shoot");
        tankBtnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankBtnShootActionPerformed(evt);
            }
        });

        tankBtnMissile.setText("Missile Operation");
        tankBtnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankBtnMissileActionPerformed(evt);
            }
        });

        tankBtnRadar.setText("Radar Operation");
        tankBtnRadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankBtnRadarActionPerformed(evt);
            }
        });

        tankBtnRotate.setText("Rotate Shooting");
        tankBtnRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankBtnRotateActionPerformed(evt);
            }
        });

        tankCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        tankCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        tankCheckBox.setText("Position");

        tankTextArea.setColumns(20);
        tankTextArea.setRows(5);
        jScrollPane1.setViewportView(tankTextArea);

        tankTextFieldMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankTextFieldMsgActionPerformed(evt);
            }
        });

        tankBtnSend.setText("Send");
        tankBtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankBtnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tankLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tankTextFieldClear, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tankBtnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tankBtnMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tankTextFieldMsg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tankBtnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(tankBtnRadar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tankBtnRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                            .addComponent(tankCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tankTextFieldClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tankBtnShoot)
                    .addComponent(tankBtnMissile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tankBtnRadar)
                    .addComponent(tankBtnRotate)
                    .addComponent(tankCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tankTextFieldMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tankBtnSend))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tankBtnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankBtnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankBtnShootActionPerformed

    private void tankBtnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankBtnMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankBtnMissileActionPerformed

    private void tankBtnRadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankBtnRadarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankBtnRadarActionPerformed

    private void tankBtnRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankBtnRotateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankBtnRotateActionPerformed

    private void tankTextFieldMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankTextFieldMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankTextFieldMsgActionPerformed

    private void tankBtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankBtnSendActionPerformed
        mainController.obseverMessage("Tank", tankTextFieldMsg.getText());
        tankTextFieldMsg.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_tankBtnSendActionPerformed

    private void tankTextFieldClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankTextFieldClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tankTextFieldClearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tankBtnMissile;
    private javax.swing.JButton tankBtnRadar;
    private javax.swing.JButton tankBtnRotate;
    private javax.swing.JButton tankBtnSend;
    private javax.swing.JButton tankBtnShoot;
    private javax.swing.JCheckBox tankCheckBox;
    private javax.swing.JLabel tankLabel;
    private javax.swing.JTextArea tankTextArea;
    private javax.swing.JTextField tankTextFieldClear;
    private javax.swing.JTextField tankTextFieldMsg;
    // End of variables declaration//GEN-END:variables
}
